-- Auto-generated by tools/musicdna/backfill_year_and_canon.mjs
-- Review the CSV before applying. 31 songs will be updated.

BEGIN;
UPDATE public.songs SET canon_score = 72, updated_at = now() WHERE id = 'a1000001-0000-0000-0000-000000000002';
UPDATE public.songs SET canon_score = 82, updated_at = now() WHERE id = '0e64f6a2-d17d-4c72-9139-15ace4129c5f';
UPDATE public.songs SET canon_score = 78, updated_at = now() WHERE id = '70af60ec-dd68-4f9c-974d-ff4f7859b994';
UPDATE public.songs SET canon_score = 58, updated_at = now() WHERE id = 'e4950cdf-58e4-467c-ab4d-1e2ae074c57b';
UPDATE public.songs SET canon_score = 82, updated_at = now() WHERE id = 'f602b363-0dfe-4f0a-b993-81a96a63a715';
UPDATE public.songs SET canon_score = 83, updated_at = now() WHERE id = 'aeff4516-3fed-4739-92fd-d3cb46e48e2f';
UPDATE public.songs SET canon_score = 78, updated_at = now() WHERE id = 'f7dbe172-5201-47bd-b9da-b0f1509c7e2b';
UPDATE public.songs SET canon_score = 68, updated_at = now() WHERE id = '2a2aaf43-f979-401f-b8bd-d41678ee8cd1';
UPDATE public.songs SET canon_score = 72, updated_at = now() WHERE id = 'b4f51a31-89f6-400c-a3a8-787cd09e9134';
UPDATE public.songs SET canon_score = 68, updated_at = now() WHERE id = '58a56f9d-7118-474e-9369-328517dbde7c';
UPDATE public.songs SET canon_score = 80, updated_at = now() WHERE id = '10d87090-d509-49be-a9ee-340a993c3241';
UPDATE public.songs SET canon_score = 85, updated_at = now() WHERE id = '0a862dd7-90e0-43f8-b87b-74b4bb19916b';
UPDATE public.songs SET canon_score = 98, updated_at = now() WHERE id = '3807ed5c-0eac-4444-b453-211c7ea2f226';
UPDATE public.songs SET canon_score = 88, updated_at = now() WHERE id = '066887a8-4c41-41b4-86a1-cfbaa1a72c90';
UPDATE public.songs SET canon_score = 80, updated_at = now() WHERE id = '6f6b158e-74ed-4556-850e-7f1c1e4c76b0';
UPDATE public.songs SET canon_score = 93, updated_at = now() WHERE id = 'f5d34434-7030-43c6-a1fa-490bac74bdee';
UPDATE public.songs SET canon_score = 92, updated_at = now() WHERE id = '8bbd45c4-705a-48ff-88de-30945f4865ee';
UPDATE public.songs SET canon_score = 93, updated_at = now() WHERE id = 'cf3c0bb7-e834-441c-bb7f-fef7bdc3741f';
UPDATE public.songs SET canon_score = 83, updated_at = now() WHERE id = '6d119e3a-f711-46b9-9ade-76a62063fa50';
UPDATE public.songs SET canon_score = 95, updated_at = now() WHERE id = '535776cd-72a7-4d7f-89d4-a856419b6262';
UPDATE public.songs SET canon_score = 40, updated_at = now() WHERE id = '95ed3777-0d34-420b-a194-f2f59872be89';
UPDATE public.songs SET canon_score = 55, updated_at = now() WHERE id = '9cf76d96-0ecd-4a9f-ba9e-2f2fa60160cf';
UPDATE public.songs SET canon_score = 78, updated_at = now() WHERE id = 'd62679a0-ea56-4c38-bbcb-a04fea4de13e';
UPDATE public.songs SET canon_score = 83, updated_at = now() WHERE id = '2fb07543-3c0b-4a78-b274-151b889a5ce6';
UPDATE public.songs SET canon_score = 68, updated_at = now() WHERE id = '3839c36a-691e-47f2-8d9b-686128055748';
UPDATE public.songs SET canon_score = 82, updated_at = now() WHERE id = '6399473d-bcd0-485d-a7e1-1bc04007b1c6';
UPDATE public.songs SET canon_score = 82, updated_at = now() WHERE id = '78f9fbe3-8022-4b0b-abf8-e98f979975d8';
UPDATE public.songs SET canon_score = 85, updated_at = now() WHERE id = 'dc8a7f8a-f7fb-46ad-b127-4372119ad460';
UPDATE public.songs SET canon_score = 80, updated_at = now() WHERE id = '8636ee91-6e9f-4f34-b46c-0b345893c121';
UPDATE public.songs SET canon_score = 70, updated_at = now() WHERE id = '6a06b74f-7161-492e-b492-6f2fa0c468d8';
UPDATE public.songs SET canon_score = 78, updated_at = now() WHERE id = '706cc200-c760-42a9-9268-57babc11bbb6';
COMMIT;
