/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MeRouteImport } from './routes/me'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSessionIdRouteImport } from './routes/s.$sessionId'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Authenticated1980RouteImport } from './routes/_authenticated/1980'
import { Route as ApiV1SessionsRouteImport } from './routes/api/v1/sessions'
import { Route as ApiV1SessionRouteImport } from './routes/api/v1/session'
import { Route as ApiV1AccountRouteImport } from './routes/api/v1/account'
import { Route as ApiV1ShareTokenRouteImport } from './routes/api/v1/share.$token'
import { Route as ApiV1SessionIdRouteImport } from './routes/api/v1/session.$id'
import { Route as ApiV1OnboardingReactRouteImport } from './routes/api/v1/onboarding.react'
import { Route as ApiV1OnboardingOpenerRouteImport } from './routes/api/v1/onboarding.opener'
import { Route as ApiPublicTestActionRouteImport } from './routes/api/public/test/$action'
import { Route as ApiV1SessionIdRevealRouteImport } from './routes/api/v1/session.$id.reveal'
import { Route as ApiV1SessionIdNextRouteImport } from './routes/api/v1/session.$id.next'
import { Route as ApiV1SessionIdChoiceRouteImport } from './routes/api/v1/session.$id.choice'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSessionIdRoute = SSessionIdRouteImport.update({
  id: '/s/$sessionId',
  path: '/s/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Authenticated1980Route = Authenticated1980RouteImport.update({
  id: '/1980',
  path: '/1980',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiV1SessionsRoute = ApiV1SessionsRouteImport.update({
  id: '/api/v1/sessions',
  path: '/api/v1/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SessionRoute = ApiV1SessionRouteImport.update({
  id: '/api/v1/session',
  path: '/api/v1/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AccountRoute = ApiV1AccountRouteImport.update({
  id: '/api/v1/account',
  path: '/api/v1/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ShareTokenRoute = ApiV1ShareTokenRouteImport.update({
  id: '/api/v1/share/$token',
  path: '/api/v1/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SessionIdRoute = ApiV1SessionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1SessionRoute,
} as any)
const ApiV1OnboardingReactRoute = ApiV1OnboardingReactRouteImport.update({
  id: '/api/v1/onboarding/react',
  path: '/api/v1/onboarding/react',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OnboardingOpenerRoute = ApiV1OnboardingOpenerRouteImport.update({
  id: '/api/v1/onboarding/opener',
  path: '/api/v1/onboarding/opener',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestActionRoute = ApiPublicTestActionRouteImport.update({
  id: '/api/public/test/$action',
  path: '/api/public/test/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SessionIdRevealRoute = ApiV1SessionIdRevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => ApiV1SessionIdRoute,
} as any)
const ApiV1SessionIdNextRoute = ApiV1SessionIdNextRouteImport.update({
  id: '/next',
  path: '/next',
  getParentRoute: () => ApiV1SessionIdRoute,
} as any)
const ApiV1SessionIdChoiceRoute = ApiV1SessionIdChoiceRouteImport.update({
  id: '/choice',
  path: '/choice',
  getParentRoute: () => ApiV1SessionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/1980': typeof Authenticated1980Route
  '/admin': typeof AuthenticatedAdminRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/s/$sessionId': typeof SSessionIdRoute
  '/api/v1/account': typeof ApiV1AccountRoute
  '/api/v1/session': typeof ApiV1SessionRouteWithChildren
  '/api/v1/sessions': typeof ApiV1SessionsRoute
  '/api/public/test/$action': typeof ApiPublicTestActionRoute
  '/api/v1/onboarding/opener': typeof ApiV1OnboardingOpenerRoute
  '/api/v1/onboarding/react': typeof ApiV1OnboardingReactRoute
  '/api/v1/session/$id': typeof ApiV1SessionIdRouteWithChildren
  '/api/v1/share/$token': typeof ApiV1ShareTokenRoute
  '/api/v1/session/$id/choice': typeof ApiV1SessionIdChoiceRoute
  '/api/v1/session/$id/next': typeof ApiV1SessionIdNextRoute
  '/api/v1/session/$id/reveal': typeof ApiV1SessionIdRevealRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/1980': typeof Authenticated1980Route
  '/admin': typeof AuthenticatedAdminRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/s/$sessionId': typeof SSessionIdRoute
  '/api/v1/account': typeof ApiV1AccountRoute
  '/api/v1/session': typeof ApiV1SessionRouteWithChildren
  '/api/v1/sessions': typeof ApiV1SessionsRoute
  '/api/public/test/$action': typeof ApiPublicTestActionRoute
  '/api/v1/onboarding/opener': typeof ApiV1OnboardingOpenerRoute
  '/api/v1/onboarding/react': typeof ApiV1OnboardingReactRoute
  '/api/v1/session/$id': typeof ApiV1SessionIdRouteWithChildren
  '/api/v1/share/$token': typeof ApiV1ShareTokenRoute
  '/api/v1/session/$id/choice': typeof ApiV1SessionIdChoiceRoute
  '/api/v1/session/$id/next': typeof ApiV1SessionIdNextRoute
  '/api/v1/session/$id/reveal': typeof ApiV1SessionIdRevealRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/1980': typeof Authenticated1980Route
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/s/$sessionId': typeof SSessionIdRoute
  '/api/v1/account': typeof ApiV1AccountRoute
  '/api/v1/session': typeof ApiV1SessionRouteWithChildren
  '/api/v1/sessions': typeof ApiV1SessionsRoute
  '/api/public/test/$action': typeof ApiPublicTestActionRoute
  '/api/v1/onboarding/opener': typeof ApiV1OnboardingOpenerRoute
  '/api/v1/onboarding/react': typeof ApiV1OnboardingReactRoute
  '/api/v1/session/$id': typeof ApiV1SessionIdRouteWithChildren
  '/api/v1/share/$token': typeof ApiV1ShareTokenRoute
  '/api/v1/session/$id/choice': typeof ApiV1SessionIdChoiceRoute
  '/api/v1/session/$id/next': typeof ApiV1SessionIdNextRoute
  '/api/v1/session/$id/reveal': typeof ApiV1SessionIdRevealRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/me'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/1980'
    | '/admin'
    | '/profile'
    | '/s/$sessionId'
    | '/api/v1/account'
    | '/api/v1/session'
    | '/api/v1/sessions'
    | '/api/public/test/$action'
    | '/api/v1/onboarding/opener'
    | '/api/v1/onboarding/react'
    | '/api/v1/session/$id'
    | '/api/v1/share/$token'
    | '/api/v1/session/$id/choice'
    | '/api/v1/session/$id/next'
    | '/api/v1/session/$id/reveal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/me'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/1980'
    | '/admin'
    | '/profile'
    | '/s/$sessionId'
    | '/api/v1/account'
    | '/api/v1/session'
    | '/api/v1/sessions'
    | '/api/public/test/$action'
    | '/api/v1/onboarding/opener'
    | '/api/v1/onboarding/react'
    | '/api/v1/session/$id'
    | '/api/v1/share/$token'
    | '/api/v1/session/$id/choice'
    | '/api/v1/session/$id/next'
    | '/api/v1/session/$id/reveal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/me'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/_authenticated/1980'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/s/$sessionId'
    | '/api/v1/account'
    | '/api/v1/session'
    | '/api/v1/sessions'
    | '/api/public/test/$action'
    | '/api/v1/onboarding/opener'
    | '/api/v1/onboarding/react'
    | '/api/v1/session/$id'
    | '/api/v1/share/$token'
    | '/api/v1/session/$id/choice'
    | '/api/v1/session/$id/next'
    | '/api/v1/session/$id/reveal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MeRoute: typeof MeRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  SSessionIdRoute: typeof SSessionIdRoute
  ApiV1AccountRoute: typeof ApiV1AccountRoute
  ApiV1SessionRoute: typeof ApiV1SessionRouteWithChildren
  ApiV1SessionsRoute: typeof ApiV1SessionsRoute
  ApiPublicTestActionRoute: typeof ApiPublicTestActionRoute
  ApiV1OnboardingOpenerRoute: typeof ApiV1OnboardingOpenerRoute
  ApiV1OnboardingReactRoute: typeof ApiV1OnboardingReactRoute
  ApiV1ShareTokenRoute: typeof ApiV1ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$sessionId': {
      id: '/s/$sessionId'
      path: '/s/$sessionId'
      fullPath: '/s/$sessionId'
      preLoaderRoute: typeof SSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/1980': {
      id: '/_authenticated/1980'
      path: '/1980'
      fullPath: '/1980'
      preLoaderRoute: typeof Authenticated1980RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/v1/sessions': {
      id: '/api/v1/sessions'
      path: '/api/v1/sessions'
      fullPath: '/api/v1/sessions'
      preLoaderRoute: typeof ApiV1SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/session': {
      id: '/api/v1/session'
      path: '/api/v1/session'
      fullPath: '/api/v1/session'
      preLoaderRoute: typeof ApiV1SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/account': {
      id: '/api/v1/account'
      path: '/api/v1/account'
      fullPath: '/api/v1/account'
      preLoaderRoute: typeof ApiV1AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/share/$token': {
      id: '/api/v1/share/$token'
      path: '/api/v1/share/$token'
      fullPath: '/api/v1/share/$token'
      preLoaderRoute: typeof ApiV1ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/session/$id': {
      id: '/api/v1/session/$id'
      path: '/$id'
      fullPath: '/api/v1/session/$id'
      preLoaderRoute: typeof ApiV1SessionIdRouteImport
      parentRoute: typeof ApiV1SessionRoute
    }
    '/api/v1/onboarding/react': {
      id: '/api/v1/onboarding/react'
      path: '/api/v1/onboarding/react'
      fullPath: '/api/v1/onboarding/react'
      preLoaderRoute: typeof ApiV1OnboardingReactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/onboarding/opener': {
      id: '/api/v1/onboarding/opener'
      path: '/api/v1/onboarding/opener'
      fullPath: '/api/v1/onboarding/opener'
      preLoaderRoute: typeof ApiV1OnboardingOpenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test/$action': {
      id: '/api/public/test/$action'
      path: '/api/public/test/$action'
      fullPath: '/api/public/test/$action'
      preLoaderRoute: typeof ApiPublicTestActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/session/$id/reveal': {
      id: '/api/v1/session/$id/reveal'
      path: '/reveal'
      fullPath: '/api/v1/session/$id/reveal'
      preLoaderRoute: typeof ApiV1SessionIdRevealRouteImport
      parentRoute: typeof ApiV1SessionIdRoute
    }
    '/api/v1/session/$id/next': {
      id: '/api/v1/session/$id/next'
      path: '/next'
      fullPath: '/api/v1/session/$id/next'
      preLoaderRoute: typeof ApiV1SessionIdNextRouteImport
      parentRoute: typeof ApiV1SessionIdRoute
    }
    '/api/v1/session/$id/choice': {
      id: '/api/v1/session/$id/choice'
      path: '/choice'
      fullPath: '/api/v1/session/$id/choice'
      preLoaderRoute: typeof ApiV1SessionIdChoiceRouteImport
      parentRoute: typeof ApiV1SessionIdRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  Authenticated1980Route: typeof Authenticated1980Route
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  Authenticated1980Route: Authenticated1980Route,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiV1SessionIdRouteChildren {
  ApiV1SessionIdChoiceRoute: typeof ApiV1SessionIdChoiceRoute
  ApiV1SessionIdNextRoute: typeof ApiV1SessionIdNextRoute
  ApiV1SessionIdRevealRoute: typeof ApiV1SessionIdRevealRoute
}

const ApiV1SessionIdRouteChildren: ApiV1SessionIdRouteChildren = {
  ApiV1SessionIdChoiceRoute: ApiV1SessionIdChoiceRoute,
  ApiV1SessionIdNextRoute: ApiV1SessionIdNextRoute,
  ApiV1SessionIdRevealRoute: ApiV1SessionIdRevealRoute,
}

const ApiV1SessionIdRouteWithChildren = ApiV1SessionIdRoute._addFileChildren(
  ApiV1SessionIdRouteChildren,
)

interface ApiV1SessionRouteChildren {
  ApiV1SessionIdRoute: typeof ApiV1SessionIdRouteWithChildren
}

const ApiV1SessionRouteChildren: ApiV1SessionRouteChildren = {
  ApiV1SessionIdRoute: ApiV1SessionIdRouteWithChildren,
}

const ApiV1SessionRouteWithChildren = ApiV1SessionRoute._addFileChildren(
  ApiV1SessionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MeRoute: MeRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  SSessionIdRoute: SSessionIdRoute,
  ApiV1AccountRoute: ApiV1AccountRoute,
  ApiV1SessionRoute: ApiV1SessionRouteWithChildren,
  ApiV1SessionsRoute: ApiV1SessionsRoute,
  ApiPublicTestActionRoute: ApiPublicTestActionRoute,
  ApiV1OnboardingOpenerRoute: ApiV1OnboardingOpenerRoute,
  ApiV1OnboardingReactRoute: ApiV1OnboardingReactRoute,
  ApiV1ShareTokenRoute: ApiV1ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
