// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udycgnhvaanemhrchbuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkeWNnbmh2YWFuZW1ocmNoYnVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA3MDM5MjQsImV4cCI6MjA5NjI3OTkyNH0.tb6Q1s2d29sJslJYb0oAOtOEKw-n2yLkhtBRk1ByoOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// `localStorage` is only defined in the browser. This module can be pulled
// into the server module graph (e.g. via a `.functions.ts` that imports it),
// so guard the storage reference to avoid a `ReferenceError: localStorage is
// not defined` when the module is evaluated on the server.
const isBrowser = typeof window !== "undefined";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? window.localStorage : undefined,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
  }
});